const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.Pin,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Behaviors.Bullet,
		C3.Behaviors.scrollto,
		C3.Behaviors.lunarray_LiteTween,
		C3.Behaviors.Fade,
		C3.Plugins.Particles,
		C3.Plugins.Spritefont2,
		C3.Plugins.TiledBg,
		C3.Plugins.lobahGameSDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Physics.Acts.CreateLimitedRevoluteJoint,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Physics.Acts.SetSteppingMode,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Behaviors.Physics.Acts.ApplyImpulse,
		C3.Behaviors.Bullet.Acts.SetGravity,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Physics.Acts.ApplyImpulseToward,
		C3.Behaviors.Physics.Exps.VelocityX,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Behaviors.lunarray_LiteTween.Cnds.OnEnd,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Physics.Cnds.IsEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.lobahGameSDK.Acts.AddScore,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.TypeScriptInEvents.Sceneadapter_Event1_Act2
	];
};
self.C3_JsPropNameTable = [
	{Physics: 0},
	{ExtraRope1: 0},
	{ExtraRope10: 0},
	{ExtraRope11: 0},
	{ExtraRope12: 0},
	{ExtraRope13: 0},
	{ExtraRope14: 0},
	{ExtraRope15: 0},
	{ExtraRope16: 0},
	{ExtraRope17: 0},
	{ExtraRope2: 0},
	{ExtraRope3: 0},
	{ExtraRope4: 0},
	{ExtraRope5: 0},
	{ExtraRope6: 0},
	{ExtraRope7: 0},
	{ExtraRope8: 0},
	{ExtraRope9: 0},
	{Rope1: 0},
	{Rope10: 0},
	{Rope11: 0},
	{Rope12: 0},
	{Rope2: 0},
	{Rope3: 0},
	{Rope4: 0},
	{Rope5: 0},
	{Rope6: 0},
	{Rope7: 0},
	{Rope8: 0},
	{Rope9: 0},
	{RopePin1: 0},
	{RopePin2: 0},
	{RopePin3: 0},
	{BackBtn: 0},
	{GravityButton: 0},
	{touchable: 0},
	{Level10BTN: 0},
	{Pin: 0},
	{Level10Stars: 0},
	{Level11BTN: 0},
	{Level11Stars: 0},
	{Level12BTN: 0},
	{Level12Stars: 0},
	{Level13BTN: 0},
	{Level13Stars: 0},
	{Level14BTN: 0},
	{Level14Stars: 0},
	{Level15BTN: 0},
	{Level15Stars: 0},
	{Level16BTN: 0},
	{Level16Stars: 0},
	{Level17BTN: 0},
	{Level17Stars: 0},
	{Level18BTN: 0},
	{Level18Stars: 0},
	{Level19BTN: 0},
	{Level19Stars: 0},
	{Level1BTN: 0},
	{Level1Stars: 0},
	{Level20BTN: 0},
	{Level20Stars: 0},
	{Level21BTN: 0},
	{Level21Stars: 0},
	{Level22BTN: 0},
	{Level22Stars: 0},
	{Level23BTN: 0},
	{Level23Stars: 0},
	{Level24BTN: 0},
	{Level24Stars: 0},
	{Level25BTN: 0},
	{Level25Stars: 0},
	{Level2BTN: 0},
	{Level2Stars: 0},
	{Level3BTN: 0},
	{Level3Stars: 0},
	{Level4BTN: 0},
	{Level4Stars: 0},
	{Level5BTN: 0},
	{Level5Stars: 0},
	{Level6BTN: 0},
	{Level6Stars: 0},
	{Level7BTN: 0},
	{Level7Stars: 0},
	{Level8BTN: 0},
	{Level8Stars: 0},
	{Level9BTN: 0},
	{Level9Stars: 0},
	{MenuBtn: 0},
	{NextBtn: 0},
	{Sine: 0},
	{PlayBtn: 0},
	{RestartBtn: 0},
	{RestartBtnHud: 0},
	{SoundBtn: 0},
	{Audio: 0},
	{Browser: 0},
	{LocalStorage: 0},
	{Touch: 0},
	{AngledPlatform: 0},
	{BouncerSpring: 0},
	{Bullet: 0},
	{BubbleCandy: 0},
	{Bounce: 0},
	{ScrollTo: 0},
	{CandyGame: 0},
	{LiteTween: 0},
	{CloseBk1: 0},
	{CloseBk2: 0},
	{CollitionsFloor: 0},
	{Fade: 0},
	{CompanyLogo: 0},
	{CubeBox: 0},
	{CutHandInstructions: 0},
	{CutInstructions: 0},
	{ElectricEffect: 0},
	{EndStarsHud: 0},
	{GameBackground: 0},
	{GameBubble: 0},
	{eat: 0},
	{Sine2: 0},
	{GamePlayer: 0},
	{GameStar: 0},
	{GameTittle: 0},
	{GravityInstruction: 0},
	{HandInstruction: 0},
	{JellyBlock: 0},
	{JellyDestroyEffect: 0},
	{JellyParticles: 0},
	{LaserObstacle: 0},
	{LevelCompleted: 0},
	{LevelFailed: 0},
	{LevelParticles: 0},
	{LevelSelectBackground: 0},
	{LevelSelectPlayer: 0},
	{LevelStarsFont: 0},
	{LevelTotalStars: 0},
	{MenuBackground: 0},
	{MenuCandy: 0},
	{MenuParticles: 0},
	{MenuPlayer: 0},
	{MenuPlayerEyes: 0},
	{MenuPlayerShadow: 0},
	{MenuStarHud: 0},
	{MenuTreeA: 0},
	{MenuTreeB: 0},
	{MenuTreeC: 0},
	{MenuTreeD: 0},
	{MenuTreeE: 0},
	{MovingBubble: 0},
	{ParticlesEat: 0},
	{Platform: 0},
	{Platform1: 0},
	{Platform2: 0},
	{Platform3: 0},
	{Platform4: 0},
	{Platform5: 0},
	{Platform6: 0},
	{Platform9: 0},
	{Platform8: 0},
	{PlayerShadow: 0},
	{PlayerShadow2: 0},
	{PortalExit: 0},
	{PortalGate: 0},
	{RotateScreen: 0},
	{SliceEffect: 0},
	{SpikeObstacle: 0},
	{StarParticles: 0},
	{StarsHud: 0},
	{TransitionEffect: 0},
	{TransitionEffectBk: 0},
	{VfxGold: 0},
	{lobahGameSDK: 0},
	{RopeFamily: 0},
	{ExtraRopeFamily: 0},
	{SoundVariable: 0},
	{IsScreenRotate: 0},
	{GravityON: 0},
	{FinalSize: 0},
	{TransitionDuration: 0},
	{RopeDestroy: 0},
	{InitialY: 0},
	{Initialx: 0},
	{Win: 0},
	{LevelVariable: 0},
	{Failed: 0},
	{EndLevel: 0},
	{Complete: 0},
	{GameOver: 0},
	{EndStars: 0},
	{GlobalStars: 0},
	{Level25star: 0},
	{Level24star: 0},
	{Level23star: 0},
	{Level22star: 0},
	{Level21star: 0},
	{Level20star: 0},
	{Level19star: 0},
	{Level18star: 0},
	{Level17star: 0},
	{Level16star: 0},
	{Level15star: 0},
	{Level14star: 0},
	{Level13star: 0},
	{Level12star: 0},
	{Level11star: 0},
	{Level10star: 0},
	{Level9star: 0},
	{Level8star: 0},
	{Level7star: 0},
	{Level6star: 0},
	{Level5star: 0},
	{Level4star: 0},
	{Level3star: 0},
	{Level2star: 0},
	{Level1star: 0},
	{adapter: 0},
	{adapterValue: 0},
	{delayAdapter: 0}
];

self.InstanceType = {
	ExtraRope1: class extends self.ISpriteInstance {},
	ExtraRope10: class extends self.ISpriteInstance {},
	ExtraRope11: class extends self.ISpriteInstance {},
	ExtraRope12: class extends self.ISpriteInstance {},
	ExtraRope13: class extends self.ISpriteInstance {},
	ExtraRope14: class extends self.ISpriteInstance {},
	ExtraRope15: class extends self.ISpriteInstance {},
	ExtraRope16: class extends self.ISpriteInstance {},
	ExtraRope17: class extends self.ISpriteInstance {},
	ExtraRope2: class extends self.ISpriteInstance {},
	ExtraRope3: class extends self.ISpriteInstance {},
	ExtraRope4: class extends self.ISpriteInstance {},
	ExtraRope5: class extends self.ISpriteInstance {},
	ExtraRope6: class extends self.ISpriteInstance {},
	ExtraRope7: class extends self.ISpriteInstance {},
	ExtraRope8: class extends self.ISpriteInstance {},
	ExtraRope9: class extends self.ISpriteInstance {},
	Rope1: class extends self.ISpriteInstance {},
	Rope10: class extends self.ISpriteInstance {},
	Rope11: class extends self.ISpriteInstance {},
	Rope12: class extends self.ISpriteInstance {},
	Rope2: class extends self.ISpriteInstance {},
	Rope3: class extends self.ISpriteInstance {},
	Rope4: class extends self.ISpriteInstance {},
	Rope5: class extends self.ISpriteInstance {},
	Rope6: class extends self.ISpriteInstance {},
	Rope7: class extends self.ISpriteInstance {},
	Rope8: class extends self.ISpriteInstance {},
	Rope9: class extends self.ISpriteInstance {},
	RopePin1: class extends self.ISpriteInstance {},
	RopePin2: class extends self.ISpriteInstance {},
	RopePin3: class extends self.ISpriteInstance {},
	BackBtn: class extends self.ISpriteInstance {},
	GravityButton: class extends self.ISpriteInstance {},
	Level10BTN: class extends self.ISpriteInstance {},
	Level10Stars: class extends self.ISpriteInstance {},
	Level11BTN: class extends self.ISpriteInstance {},
	Level11Stars: class extends self.ISpriteInstance {},
	Level12BTN: class extends self.ISpriteInstance {},
	Level12Stars: class extends self.ISpriteInstance {},
	Level13BTN: class extends self.ISpriteInstance {},
	Level13Stars: class extends self.ISpriteInstance {},
	Level14BTN: class extends self.ISpriteInstance {},
	Level14Stars: class extends self.ISpriteInstance {},
	Level15BTN: class extends self.ISpriteInstance {},
	Level15Stars: class extends self.ISpriteInstance {},
	Level16BTN: class extends self.ISpriteInstance {},
	Level16Stars: class extends self.ISpriteInstance {},
	Level17BTN: class extends self.ISpriteInstance {},
	Level17Stars: class extends self.ISpriteInstance {},
	Level18BTN: class extends self.ISpriteInstance {},
	Level18Stars: class extends self.ISpriteInstance {},
	Level19BTN: class extends self.ISpriteInstance {},
	Level19Stars: class extends self.ISpriteInstance {},
	Level1BTN: class extends self.ISpriteInstance {},
	Level1Stars: class extends self.ISpriteInstance {},
	Level20BTN: class extends self.ISpriteInstance {},
	Level20Stars: class extends self.ISpriteInstance {},
	Level21BTN: class extends self.ISpriteInstance {},
	Level21Stars: class extends self.ISpriteInstance {},
	Level22BTN: class extends self.ISpriteInstance {},
	Level22Stars: class extends self.ISpriteInstance {},
	Level23BTN: class extends self.ISpriteInstance {},
	Level23Stars: class extends self.ISpriteInstance {},
	Level24BTN: class extends self.ISpriteInstance {},
	Level24Stars: class extends self.ISpriteInstance {},
	Level25BTN: class extends self.ISpriteInstance {},
	Level25Stars: class extends self.ISpriteInstance {},
	Level2BTN: class extends self.ISpriteInstance {},
	Level2Stars: class extends self.ISpriteInstance {},
	Level3BTN: class extends self.ISpriteInstance {},
	Level3Stars: class extends self.ISpriteInstance {},
	Level4BTN: class extends self.ISpriteInstance {},
	Level4Stars: class extends self.ISpriteInstance {},
	Level5BTN: class extends self.ISpriteInstance {},
	Level5Stars: class extends self.ISpriteInstance {},
	Level6BTN: class extends self.ISpriteInstance {},
	Level6Stars: class extends self.ISpriteInstance {},
	Level7BTN: class extends self.ISpriteInstance {},
	Level7Stars: class extends self.ISpriteInstance {},
	Level8BTN: class extends self.ISpriteInstance {},
	Level8Stars: class extends self.ISpriteInstance {},
	Level9BTN: class extends self.ISpriteInstance {},
	Level9Stars: class extends self.ISpriteInstance {},
	MenuBtn: class extends self.ISpriteInstance {},
	NextBtn: class extends self.ISpriteInstance {},
	PlayBtn: class extends self.ISpriteInstance {},
	RestartBtn: class extends self.ISpriteInstance {},
	RestartBtnHud: class extends self.ISpriteInstance {},
	SoundBtn: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	AngledPlatform: class extends self.ISpriteInstance {},
	BouncerSpring: class extends self.ISpriteInstance {},
	BubbleCandy: class extends self.ISpriteInstance {},
	CandyGame: class extends self.ISpriteInstance {},
	CloseBk1: class extends self.ISpriteInstance {},
	CloseBk2: class extends self.ISpriteInstance {},
	CollitionsFloor: class extends self.ISpriteInstance {},
	CompanyLogo: class extends self.ISpriteInstance {},
	CubeBox: class extends self.ISpriteInstance {},
	CutHandInstructions: class extends self.ISpriteInstance {},
	CutInstructions: class extends self.ISpriteInstance {},
	ElectricEffect: class extends self.ISpriteInstance {},
	EndStarsHud: class extends self.ISpriteInstance {},
	GameBackground: class extends self.ISpriteInstance {},
	GameBubble: class extends self.ISpriteInstance {},
	GamePlayer: class extends self.ISpriteInstance {},
	GameStar: class extends self.ISpriteInstance {},
	GameTittle: class extends self.ISpriteInstance {},
	GravityInstruction: class extends self.ISpriteInstance {},
	HandInstruction: class extends self.ISpriteInstance {},
	JellyBlock: class extends self.ISpriteInstance {},
	JellyDestroyEffect: class extends self.ISpriteInstance {},
	JellyParticles: class extends self.IParticlesInstance {},
	LaserObstacle: class extends self.ISpriteInstance {},
	LevelCompleted: class extends self.ISpriteInstance {},
	LevelFailed: class extends self.ISpriteInstance {},
	LevelParticles: class extends self.IParticlesInstance {},
	LevelSelectBackground: class extends self.ISpriteInstance {},
	LevelSelectPlayer: class extends self.ISpriteInstance {},
	LevelStarsFont: class extends self.ISpriteFontInstance {},
	LevelTotalStars: class extends self.ISpriteInstance {},
	MenuBackground: class extends self.ISpriteInstance {},
	MenuCandy: class extends self.ISpriteInstance {},
	MenuParticles: class extends self.IParticlesInstance {},
	MenuPlayer: class extends self.ISpriteInstance {},
	MenuPlayerEyes: class extends self.ISpriteInstance {},
	MenuPlayerShadow: class extends self.ISpriteInstance {},
	MenuStarHud: class extends self.ISpriteInstance {},
	MenuTreeA: class extends self.ISpriteInstance {},
	MenuTreeB: class extends self.ISpriteInstance {},
	MenuTreeC: class extends self.ISpriteInstance {},
	MenuTreeD: class extends self.ISpriteInstance {},
	MenuTreeE: class extends self.ISpriteInstance {},
	MovingBubble: class extends self.ISpriteInstance {},
	ParticlesEat: class extends self.IParticlesInstance {},
	Platform: class extends self.ISpriteInstance {},
	Platform1: class extends self.ISpriteInstance {},
	Platform2: class extends self.ISpriteInstance {},
	Platform3: class extends self.ISpriteInstance {},
	Platform4: class extends self.ISpriteInstance {},
	Platform5: class extends self.ISpriteInstance {},
	Platform6: class extends self.ISpriteInstance {},
	Platform9: class extends self.ISpriteInstance {},
	Platform8: class extends self.ISpriteInstance {},
	PlayerShadow: class extends self.ISpriteInstance {},
	PlayerShadow2: class extends self.ISpriteInstance {},
	PortalExit: class extends self.ISpriteInstance {},
	PortalGate: class extends self.ISpriteInstance {},
	RotateScreen: class extends self.ISpriteInstance {},
	SliceEffect: class extends self.ISpriteInstance {},
	SpikeObstacle: class extends self.ISpriteInstance {},
	StarParticles: class extends self.IParticlesInstance {},
	StarsHud: class extends self.ISpriteInstance {},
	TransitionEffect: class extends self.ISpriteInstance {},
	TransitionEffectBk: class extends self.ITiledBackgroundInstance {},
	VfxGold: class extends self.ISpriteInstance {},
	lobahGameSDK: class extends C3.Plugins.lobahGameSDK.Instance {},
	RopeFamily: class extends self.ISpriteInstance {},
	ExtraRopeFamily: class extends self.ISpriteInstance {}
}