const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.TiledBg,
		C3.Behaviors.Pin,
		C3.Plugins.Arr,
		C3.Plugins.Function,
		C3.Plugins.Text,
		C3.Plugins.Particles,
		C3.Plugins.Browser,
		C3.Behaviors.Sin,
		C3.Behaviors.Fade,
		C3.Behaviors.scrollto,
		C3.Behaviors.Bullet,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.lobahGameSDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.lobahGameSDK.Acts.AddScore,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.TypeScriptInEvents.Sceneadapter_Event1_Act2
	];
};
self.C3_JsPropNameTable = [
	{isConnected: 0},
	{color: 0},
	{Dot: 0},
	{Touch: 0},
	{BG: 0},
	{Pin: 0},
	{Detector: 0},
	{Line: 0},
	{LinesUIDS: 0},
	{DotsUIDS: 0},
	{Function: 0},
	{Score_text: 0},
	{Play_button: 0},
	{Particles: 0},
	{Browser: 0},
	{Time_text: 0},
	{Pause_icon: 0},
	{Sine: 0},
	{Logo: 0},
	{Gems: 0},
	{Fade: 0},
	{Fade_menu_sprite: 0},
	{Time_icon: 0},
	{ScrollTo: 0},
	{Frame: 0},
	{Record: 0},
	{Time_out: 0},
	{ok_button: 0},
	{YourScore: 0},
	{Highscore: 0},
	{Fade2: 0},
	{Bullet: 0},
	{"2_text": 0},
	{TiledBackground: 0},
	{Music: 0},
	{Audio: 0},
	{Sprite: 0},
	{BeamEmpty_LightBrown: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Timer: 0},
	{Sprite4: 0},
	{ArmazenamentoLocal: 0},
	{lobahGameSDK: 0},
	{Dots: 0},
	{Fade_family: 0},
	{Sound: 0},
	{Combo: 0},
	{TimeGame: 0},
	{Score: 0},
	{MegScore: 0},
	{GROUND: 0},
	{ConnectedCount: 0},
	{CurrentColor: 0},
	{CurrentPos: 0},
	{Draging: 0},
	{SoundOn: 0},
	{adapter: 0},
	{adapterValue: 0},
	{delayAdapter: 0}
];

self.InstanceType = {
	Dot: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	BG: class extends self.ITiledBackgroundInstance {},
	Detector: class extends self.ISpriteInstance {},
	Line: class extends self.ISpriteInstance {},
	LinesUIDS: class extends self.IArrayInstance {},
	DotsUIDS: class extends self.IArrayInstance {},
	Function: class extends self.IInstance {},
	Score_text: class extends self.ITextInstance {},
	Play_button: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Browser: class extends self.IInstance {},
	Time_text: class extends self.ITextInstance {},
	Pause_icon: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	Gems: class extends self.ISpriteInstance {},
	Fade_menu_sprite: class extends self.ISpriteInstance {},
	Time_icon: class extends self.ISpriteInstance {},
	Frame: class extends self.ISpriteInstance {},
	Fade: class extends self.ISpriteInstance {},
	Record: class extends self.ITextInstance {},
	Time_out: class extends self.ISpriteInstance {},
	ok_button: class extends self.ISpriteInstance {},
	YourScore: class extends self.ITextInstance {},
	Highscore: class extends self.ITextInstance {},
	Fade2: class extends self.ISpriteInstance {},
	_2_text: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Music: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	BeamEmpty_LightBrown: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Timer: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	ArmazenamentoLocal: class extends self.IInstance {},
	lobahGameSDK: class extends C3.Plugins.lobahGameSDK.Instance {},
	Dots: class extends self.ISpriteInstance {},
	Fade_family: class extends self.ISpriteInstance {}
}