const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch,
		C3.Behaviors.Fade,
		C3.Plugins.Particles,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Plugins.Text,
		C3.Plugins.Browser,
		C3.Plugins.lobahGameSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.lobahGameSDK.Acts.AddScore,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.TypeScriptInEvents.Sceneadapter_Event1_Act2
	];
};
self.C3_JsPropNameTable = [
	{"8Direction": 0},
	{Bullet: 0},
	{player: 0},
	{Touch: 0},
	{wall: 0},
	{scored: 0},
	{int_rotate: 0},
	{Planet: 0},
	{Fade: 0},
	{Player_particle: 0},
	{Particles: 0},
	{BG: 0},
	{Star: 0},
	{Reward: 0},
	{LocalStorage: 0},
	{Sine: 0},
	{Play: 0},
	{Audio: 0},
	{SpriteFont_GameScore: 0},
	{Volume: 0},
	{loading: 0},
	{ScoreFA: 0},
	{Logo: 0},
	{Browser: 0},
	{back: 0},
	{back2: 0},
	{Text: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{SpriteFont: 0},
	{Sprite3: 0},
	{home: 0},
	{SpriteFont_HiScore: 0},
	{player2: 0},
	{btn_back: 0},
	{lobahGameSDK: 0},
	{BestScore: 0},
	{GameOver: 0},
	{Score: 0},
	{bulletAngle: 0},
	{adapter: 0},
	{adapterValue: 0},
	{delayAdapter: 0}
];

self.InstanceType = {
	player: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	wall: class extends self.ISpriteInstance {},
	Planet: class extends self.ISpriteInstance {},
	Player_particle: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	BG: class extends self.ISpriteInstance {},
	Star: class extends self.ISpriteInstance {},
	Reward: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Play: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	SpriteFont_GameScore: class extends self.ISpriteFontInstance {},
	Volume: class extends self.ISpriteInstance {},
	loading: class extends self.ITextInstance {},
	ScoreFA: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	back: class extends self.ISpriteInstance {},
	back2: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	SpriteFont_HiScore: class extends self.ISpriteFontInstance {},
	player2: class extends self.ISpriteInstance {},
	btn_back: class extends self.ISpriteInstance {},
	lobahGameSDK: class extends C3.Plugins.lobahGameSDK.Instance {}
}