const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Behaviors.Bullet,
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Spritefont2,
		C3.Plugins.lobahGameSDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.lobahGameSDK.Acts.AddScore,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Spritefont2.Acts.SetCharacterWidth,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.TypeScriptInEvents.Sceneadapter_Event1_Act2
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Sprite10: 0},
	{Sine: 0},
	{spawn: 0},
	{delete: 0},
	{nub: 0},
	{platform: 0},
	{gameOver: 0},
	{NAME: 0},
	{platformB: 0},
	{up: 0},
	{Rotate: 0},
	{GG: 0},
	{war1: 0},
	{war2: 0},
	{war3: 0},
	{Bullet: 0},
	{fructA: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite21: 0},
	{Sprite23: 0},
	{Sprite31: 0},
	{fruct: 0},
	{bestScore: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Array: 0},
	{Audio: 0},
	{Browser: 0},
	{Touch: 0},
	{ArmazenamentoLocal: 0},
	{SpriteFont: 0},
	{SpriteFont2: 0},
	{SpriteFont3: 0},
	{Sprite2: 0},
	{lobahGameSDK: 0},
	{sound: 0},
	{best: 0},
	{score: 0},
	{adapter: 0},
	{adapterValue: 0},
	{delayAdapter: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	spawn: class extends self.ISpriteInstance {},
	delete: class extends self.ISpriteInstance {},
	nub: class extends self.ISpriteInstance {},
	platform: class extends self.ISpriteInstance {},
	gameOver: class extends self.ISpriteInstance {},
	NAME: class extends self.ISpriteInstance {},
	platformB: class extends self.ISpriteInstance {},
	GG: class extends self.ISpriteInstance {},
	war1: class extends self.ISpriteInstance {},
	war2: class extends self.ISpriteInstance {},
	war3: class extends self.ISpriteInstance {},
	fructA: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	fruct: class extends self.ISpriteInstance {},
	bestScore: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Array: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	ArmazenamentoLocal: class extends self.IInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	SpriteFont2: class extends self.ISpriteFontInstance {},
	SpriteFont3: class extends self.ISpriteFontInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	lobahGameSDK: class extends C3.Plugins.lobahGameSDK.Instance {}
}