const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Plugins.Mouse,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.lobahGameSDK,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.lobahGameSDK.Acts.AddScore,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.TypeScriptInEvents.Sceneadapter_Event1_Act2
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Solid: 0},
	{s: 0},
	{Score: 0},
	{Footer: 0},
	{Goaler: 0},
	{orginal: 0},
	{Bullet: 0},
	{Ball: 0},
	{Mouse: 0},
	{Score_txt: 0},
	{End_wall: 0},
	{Sine: 0},
	{Play: 0},
	{Touch: 0},
	{Title: 0},
	{Sprite2: 0},
	{Hi_Score_txt: 0},
	{LocalStorage: 0},
	{Browser: 0},
	{Audio: 0},
	{BTNSoundOff: 0},
	{btn_back: 0},
	{BTNHome: 0},
	{Sprite3: 0},
	{SpriteFont: 0},
	{Sprite5: 0},
	{wall: 0},
	{Sprite4: 0},
	{Sprite7: 0},
	{Text: 0},
	{lobahGameSDK: 0},
	{Sound: 0},
	{HiScore: 0},
	{Speed: 0},
	{Run: 0},
	{adapter: 0},
	{adapterValue: 0},
	{delayAdapter: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	s: class extends self.ISpriteInstance {},
	Score: class extends self.ISpriteInstance {},
	Footer: class extends self.ISpriteInstance {},
	Goaler: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Score_txt: class extends self.ISpriteFontInstance {},
	End_wall: class extends self.ISpriteInstance {},
	Play: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Title: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Hi_Score_txt: class extends self.ISpriteFontInstance {},
	LocalStorage: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	BTNSoundOff: class extends self.ISpriteInstance {},
	btn_back: class extends self.ISpriteInstance {},
	BTNHome: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	wall: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	lobahGameSDK: class extends C3.Plugins.lobahGameSDK.Instance {}
}