const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Function,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Tween,
		C3.Behaviors.scrollto,
		C3.Plugins.TiledBg,
		C3.Behaviors.Fade,
		C3.Behaviors.Bullet,
		C3.Behaviors.Rotate,
		C3.Plugins.lobahGameSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Function.Exps.Call,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.Function.Cnds.CompareParam,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Cnds.CompareWidth,
		C3.Plugins.Function.Acts.SetReturnValue,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.lobahGameSDK.Acts.AddScore,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.CompareTouchSpeed,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Touch.Exps.AngleAt,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Exps.int,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.TypeScriptInEvents.Sceneadapter_Event1_Act2
	];
};
self.C3_JsPropNameTable = [
	{AJAX: 0},
	{array_data: 0},
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{last_rotate: 0},
	{Function: 0},
	{LocalStorage: 0},
	{Touch: 0},
	{btn_back: 0},
	{btn_close: 0},
	{bg_menu: 0},
	{type: 0},
	{btn_home: 0},
	{btn_info: 0},
	{id: 0},
	{btn_level: 0},
	{btn_menu: 0},
	{btn_music: 0},
	{btn_next: 0},
	{btn_play: 0},
	{Sine: 0},
	{btn_play_start: 0},
	{btn_restart: 0},
	{btn_sound: 0},
	{btn_speed: 0},
	{btn_undo: 0},
	{font_white: 0},
	{SpriteFont: 0},
	{SpriteFont2: 0},
	{SpriteFont3: 0},
	{background: 0},
	{placed: 0},
	{rotate: 0},
	{tile: 0},
	{target: 0},
	{maker: 0},
	{start: 0},
	{nx: 0},
	{ny: 0},
	{filled: 0},
	{is_right: 0},
	{active: 0},
	{Tween: 0},
	{pipe: 0},
	{detector_f: 0},
	{game_title: 0},
	{background2: 0},
	{header: 0},
	{level_header: 0},
	{new: 0},
	{ScrollTo: 0},
	{scroll: 0},
	{page_dots: 0},
	{leaking: 0},
	{detector: 0},
	{b_s: 0},
	{popup: 0},
	{gameover: 0},
	{progress_: 0},
	{p_l: 0},
	{p_r: 0},
	{progress_bar: 0},
	{light: 0},
	{Fade: 0},
	{Bullet: 0},
	{score_text: 0},
	{info: 0},
	{Rotate: 0},
	{loading: 0},
	{game_end: 0},
	{ID: 0},
	{last_x: 0},
	{last_y: 0},
	{last_angle: 0},
	{last_animation: 0},
	{nx2: 0},
	{ny2: 0},
	{water: 0},
	{finger: 0},
	{lobahGameSDK: 0},
	{buttons: 0},
	{water_max_speed: 0},
	{target_pipe: 0},
	{filled_pipe: 0},
	{score: 0},
	{best_score: 0},
	{state: 0},
	{fast_water: 0},
	{water_start: 0},
	{tile_size: 0},
	{index: 0},
	{last_xx: 0},
	{last_yy: 0},
	{pipe_angle: 0},
	{water_angle: 0},
	{check: 0},
	{tile_id: 0},
	{move_x: 0},
	{move_y: 0},
	{t: 0},
	{return: 0},
	{stuck: 0},
	{music: 0},
	{sound: 0},
	{cur_level: 0},
	{max_page: 0},
	{unlock_level: 0},
	{cur_page: 0},
	{total_level: 0},
	{space_x: 0},
	{space_y: 0},
	{x: 0},
	{y: 0},
	{counter: 0},
	{counter2: 0},
	{is_swiping: 0},
	{loop: 0},
	{loop_int: 0},
	{adapter: 0},
	{adapterValue: 0},
	{delayAdapter: 0}
];

self.InstanceType = {
	AJAX: class extends self.IInstance {},
	array_data: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	last_rotate: class extends self.IArrayInstance {},
	Function: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	btn_back: class extends self.ISpriteInstance {},
	btn_close: class extends self.ISpriteInstance {},
	bg_menu: class extends self.ISpriteInstance {},
	btn_home: class extends self.ISpriteInstance {},
	btn_info: class extends self.ISpriteInstance {},
	btn_level: class extends self.ISpriteInstance {},
	btn_menu: class extends self.ISpriteInstance {},
	btn_music: class extends self.ISpriteInstance {},
	btn_next: class extends self.ISpriteInstance {},
	btn_play: class extends self.ISpriteInstance {},
	btn_play_start: class extends self.ISpriteInstance {},
	btn_restart: class extends self.ISpriteInstance {},
	btn_sound: class extends self.ISpriteInstance {},
	btn_speed: class extends self.ISpriteInstance {},
	btn_undo: class extends self.ISpriteInstance {},
	font_white: class extends self.ISpriteFontInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	SpriteFont2: class extends self.ISpriteFontInstance {},
	SpriteFont3: class extends self.ISpriteFontInstance {},
	background: class extends self.ISpriteInstance {},
	tile: class extends self.ISpriteInstance {},
	pipe: class extends self.ISpriteInstance {},
	detector_f: class extends self.ISpriteInstance {},
	game_title: class extends self.ISpriteInstance {},
	background2: class extends self.ISpriteInstance {},
	header: class extends self.ISpriteInstance {},
	level_header: class extends self.ISpriteInstance {},
	new: class extends self.ISpriteInstance {},
	scroll: class extends self.ISpriteInstance {},
	page_dots: class extends self.ISpriteInstance {},
	leaking: class extends self.ISpriteInstance {},
	detector: class extends self.ISpriteInstance {},
	b_s: class extends self.ISpriteInstance {},
	popup: class extends self.ISpriteInstance {},
	gameover: class extends self.ISpriteInstance {},
	progress_: class extends self.ISpriteInstance {},
	p_l: class extends self.ISpriteInstance {},
	p_r: class extends self.ISpriteInstance {},
	progress_bar: class extends self.ITiledBackgroundInstance {},
	light: class extends self.ISpriteInstance {},
	score_text: class extends self.ISpriteInstance {},
	info: class extends self.ISpriteInstance {},
	loading: class extends self.ISpriteInstance {},
	game_end: class extends self.ISpriteInstance {},
	water: class extends self.ISpriteInstance {},
	finger: class extends self.ISpriteInstance {},
	lobahGameSDK: class extends C3.Plugins.lobahGameSDK.Instance {},
	buttons: class extends self.ISpriteInstance {}
}