const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.Touch,
		C3.Behaviors.Sin,
		C3.Behaviors.Pin,
		C3.Behaviors.Platform,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Plugins.lobahGameSDK,
		C3.Behaviors.Physics,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Cnds.IsByWall,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.lobahGameSDK.Acts.AddScore,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.lobahGameSDK.Acts.SetGameStatus,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.TypeScriptInEvents.Sceneadapter_Event1_Act2
	];
};
self.C3_JsPropNameTable = [
	{catched: 0},
	{pirana: 0},
	{dead: 0},
	{pos_y: 0},
	{speed: 0},
	{Mouse: 0},
	{Solid: 0},
	{wallRight: 0},
	{wallLeft: 0},
	{Touch: 0},
	{Sine: 0},
	{line: 0},
	{catch: 0},
	{Pin: 0},
	{Hook: 0},
	{Winch: 0},
	{bg: 0},
	{wallbottom: 0},
	{Platform: 0},
	{btnPlay: 0},
	{title: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{btnSound: 0},
	{btnBack: 0},
	{txtHighScore: 0},
	{txtMnScore: 0},
	{Audio: 0},
	{TimeBg: 0},
	{timeline: 0},
	{txtScore: 0},
	{btnHome: 0},
	{LocalStorage: 0},
	{Browser: 0},
	{Sprite: 0},
	{Text: 0},
	{lobahGameSDK: 0},
	{Pin2: 0},
	{Platform2: 0},
	{Physics: 0},
	{F_Mouse: 0},
	{LineGrow: 0},
	{Isstart: 0},
	{Islose: 0},
	{Mouse_width: 0},
	{Mouse_animation: 0},
	{pos_x: 0},
	{cooldown: 0},
	{Score: 0},
	{HighScore: 0},
	{ver: 0},
	{HighScore2: 0},
	{once: 0},
	{adapter: 0},
	{adapterValue: 0},
	{delayAdapter: 0}
];

self.InstanceType = {
	Mouse: class extends self.ISpriteInstance {},
	wallRight: class extends self.ISpriteInstance {},
	wallLeft: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	line: class extends self.ISpriteInstance {},
	Hook: class extends self.ISpriteInstance {},
	Winch: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	wallbottom: class extends self.ISpriteInstance {},
	pirana: class extends self.ISpriteInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	title: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	btnSound: class extends self.ISpriteInstance {},
	btnBack: class extends self.ISpriteInstance {},
	txtHighScore: class extends self.ISpriteFontInstance {},
	txtMnScore: class extends self.ISpriteFontInstance {},
	Audio: class extends self.IInstance {},
	TimeBg: class extends self.ISpriteInstance {},
	timeline: class extends self.ISpriteInstance {},
	txtScore: class extends self.ISpriteFontInstance {},
	btnHome: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	lobahGameSDK: class extends C3.Plugins.lobahGameSDK.Instance {},
	F_Mouse: class extends self.ISpriteInstance {}
}