const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Spritefont2,
		C3.Behaviors.scrollto,
		C3.Plugins.lobahGameSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.lobahGameSDK.Acts.AddScore,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.Browser.Acts.ExecJs,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.TypeScriptInEvents.Sceneadapter_Event1_Act2
	];
};
self.C3_JsPropNameTable = [
	{num: 0},
	{create: 0},
	{Sine: 0},
	{Box: 0},
	{Sprite: 0},
	{Touch: 0},
	{Back: 0},
	{play: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{LocalStorage: 0},
	{Hiscore_txtt: 0},
	{Audio: 0},
	{Back_Main: 0},
	{Explode02: 0},
	{ScoreBar: 0},
	{Title: 0},
	{HELP: 0},
	{Explode01: 0},
	{SC: 0},
	{BTNSound: 0},
	{BTNHome: 0},
	{Browser: 0},
	{btn_back: 0},
	{Sprite5: 0},
	{SpriteFont: 0},
	{Score_txt: 0},
	{Hi_Score: 0},
	{Text: 0},
	{ScrollTo: 0},
	{cam: 0},
	{lobahGameSDK: 0},
	{Size_bomp: 0},
	{HiScore: 0},
	{Speed: 0},
	{Sound: 0},
	{Run: 0},
	{Create: 0},
	{Score: 0},
	{adapter: 0},
	{adapterValue: 0},
	{delayAdapter: 0}
];

self.InstanceType = {
	Box: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Back: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Hiscore_txtt: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	Back_Main: class extends self.ISpriteInstance {},
	Explode02: class extends self.ISpriteInstance {},
	ScoreBar: class extends self.ISpriteInstance {},
	Title: class extends self.ISpriteInstance {},
	HELP: class extends self.ISpriteInstance {},
	Explode01: class extends self.ISpriteInstance {},
	SC: class extends self.ISpriteInstance {},
	BTNSound: class extends self.ISpriteInstance {},
	BTNHome: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	btn_back: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Score_txt: class extends self.ISpriteFontInstance {},
	Hi_Score: class extends self.ISpriteFontInstance {},
	Text: class extends self.ITextInstance {},
	cam: class extends self.ISpriteInstance {},
	lobahGameSDK: class extends C3.Plugins.lobahGameSDK.Instance {}
}