const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Pin,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Plugins.Function,
		C3.Plugins.Keyboard,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Plugins.lobahGameSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Spritefont2.Cnds.PickByUID,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.anglerotate,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Acts.RotateCounterclockwise,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.lobahGameSDK.Acts.AddScore,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.TypeScriptInEvents.Sceneadapter_Event1_Act2
	];
};
self.C3_JsPropNameTable = [
	{BG: 0},
	{speaker: 0},
	{HUD: 0},
	{SpriteFont: 0},
	{Sine: 0},
	{TAPTOSTART: 0},
	{Touch: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{Circle: 0},
	{Pin: 0},
	{Solid: 0},
	{Player: 0},
	{Bullet: 0},
	{Ball: 0},
	{HiddenBall: 0},
	{TouchAngel: 0},
	{Function: 0},
	{Keyboard: 0},
	{Fade: 0},
	{RicochetingOrange: 0},
	{Text: 0},
	{lobahGameSDK: 0},
	{GameMode: 0},
	{BestScore: 0},
	{Score: 0},
	{BallBulletSpeed: 0},
	{adapter: 0},
	{adapterValue: 0},
	{delayAdapter: 0}
];

self.InstanceType = {
	BG: class extends self.ISpriteInstance {},
	speaker: class extends self.ISpriteInstance {},
	HUD: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	TAPTOSTART: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Circle: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	HiddenBall: class extends self.ISpriteInstance {},
	TouchAngel: class extends self.ISpriteInstance {},
	Function: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	RicochetingOrange: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	lobahGameSDK: class extends C3.Plugins.lobahGameSDK.Instance {}
}