const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Behaviors.destroy,
		C3.Plugins.Particles,
		C3.Plugins.Keyboard,
		C3.Plugins.Arr,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.lobahGameSDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.RotateCounterclockwise,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Cnds.PickOverlappingPoint,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.lobahGameSDK.Acts.AddScore,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Acts.Sort,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.PickNth,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.TypeScriptInEvents.Sceneadapter_Event1_Act2
	];
};
self.C3_JsPropNameTable = [
	{btn_back: 0},
	{btn_credits: 0},
	{btn_desktop: 0},
	{btn_down: 0},
	{btn_down_impact: 0},
	{btn_left: 0},
	{Sine: 0},
	{btn_menu: 0},
	{btn_mobile: 0},
	{btn_pause: 0},
	{btn_playGame: 0},
	{btn_right: 0},
	{btn_rotate_01: 0},
	{btn_rotate_02: 0},
	{btn_social_media: 0},
	{btn_sound: 0},
	{btn_swap: 0},
	{bg_credits: 0},
	{bg_game_layout: 0},
	{bg_gameOver: 0},
	{bg_initial: 0},
	{bg_paused: 0},
	{bg_splash: 0},
	{canMove: 0},
	{block: 0},
	{board_blocks: 0},
	{deadBlocks: 0},
	{dropBlock: 0},
	{next_block1: 0},
	{next_block2: 0},
	{next_block3: 0},
	{next_block4: 0},
	{swapBlock: 0},
	{Fade: 0},
	{DestroyOutsideLayout: 0},
	{combo_SF: 0},
	{hs_level_SF: 0},
	{hs_lines_SF: 0},
	{hs_score_SF: 0},
	{labels_SF: 0},
	{level_SF: 0},
	{lines_SF: 0},
	{multiplier_SF: 0},
	{score_SF: 0},
	{ParticlesAqua: 0},
	{ParticlesBlue: 0},
	{ParticlesGreen: 0},
	{ParticlesOrange: 0},
	{ParticlesPurple: 0},
	{ParticlesRed: 0},
	{ParticlesYellow: 0},
	{board: 0},
	{blocks_white_effect: 0},
	{flash_effect: 0},
	{stars_animation: 0},
	{controls_pc_label: 0},
	{pause_screen: 0},
	{Keyboard: 0},
	{scoreArray: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{Touch: 0},
	{lobahGameSDK: 0},
	{平铺图: 0},
	{平铺图2: 0},
	{BLOCKSIZE: 0},
	{fallDelay: 0},
	{score: 0},
	{level: 0},
	{lines: 0},
	{fallScaling: 0},
	{multiplier: 0},
	{isDOWN: 0},
	{temp: 0},
	{row: 0},
	{col: 0},
	{rowCount: 0},
	{rowNum: 0},
	{clearCount: 0},
	{highScores: 0},
	{index: 0},
	{sound: 0},
	{gameMode: 0},
	{adapter: 0},
	{adapterValue: 0},
	{delayAdapter: 0}
];

self.InstanceType = {
	btn_back: class extends self.ISpriteInstance {},
	btn_credits: class extends self.ISpriteInstance {},
	btn_desktop: class extends self.ISpriteInstance {},
	btn_down: class extends self.ISpriteInstance {},
	btn_down_impact: class extends self.ISpriteInstance {},
	btn_left: class extends self.ISpriteInstance {},
	btn_menu: class extends self.ISpriteInstance {},
	btn_mobile: class extends self.ISpriteInstance {},
	btn_pause: class extends self.ISpriteInstance {},
	btn_playGame: class extends self.ISpriteInstance {},
	btn_right: class extends self.ISpriteInstance {},
	btn_rotate_01: class extends self.ISpriteInstance {},
	btn_rotate_02: class extends self.ISpriteInstance {},
	btn_social_media: class extends self.ISpriteInstance {},
	btn_sound: class extends self.ISpriteInstance {},
	btn_swap: class extends self.ISpriteInstance {},
	bg_credits: class extends self.ISpriteInstance {},
	bg_game_layout: class extends self.ISpriteInstance {},
	bg_gameOver: class extends self.ISpriteInstance {},
	bg_initial: class extends self.ISpriteInstance {},
	bg_paused: class extends self.ITiledBackgroundInstance {},
	bg_splash: class extends self.ISpriteInstance {},
	block: class extends self.ISpriteInstance {},
	board_blocks: class extends self.ISpriteInstance {},
	deadBlocks: class extends self.ISpriteInstance {},
	dropBlock: class extends self.ISpriteInstance {},
	next_block1: class extends self.ISpriteInstance {},
	next_block2: class extends self.ISpriteInstance {},
	next_block3: class extends self.ISpriteInstance {},
	next_block4: class extends self.ISpriteInstance {},
	swapBlock: class extends self.ISpriteInstance {},
	combo_SF: class extends self.ISpriteFontInstance {},
	hs_level_SF: class extends self.ISpriteFontInstance {},
	hs_lines_SF: class extends self.ISpriteFontInstance {},
	hs_score_SF: class extends self.ISpriteFontInstance {},
	labels_SF: class extends self.ISpriteFontInstance {},
	level_SF: class extends self.ISpriteFontInstance {},
	lines_SF: class extends self.ISpriteFontInstance {},
	multiplier_SF: class extends self.ISpriteFontInstance {},
	score_SF: class extends self.ISpriteFontInstance {},
	ParticlesAqua: class extends self.IParticlesInstance {},
	ParticlesBlue: class extends self.IParticlesInstance {},
	ParticlesGreen: class extends self.IParticlesInstance {},
	ParticlesOrange: class extends self.IParticlesInstance {},
	ParticlesPurple: class extends self.IParticlesInstance {},
	ParticlesRed: class extends self.IParticlesInstance {},
	ParticlesYellow: class extends self.IParticlesInstance {},
	board: class extends self.ISpriteInstance {},
	blocks_white_effect: class extends self.ISpriteInstance {},
	flash_effect: class extends self.ITiledBackgroundInstance {},
	stars_animation: class extends self.ISpriteInstance {},
	controls_pc_label: class extends self.ISpriteInstance {},
	pause_screen: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	scoreArray: class extends self.IArrayInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	lobahGameSDK: class extends C3.Plugins.lobahGameSDK.Instance {},
	平铺图: class extends self.ITiledBackgroundInstance {},
	平铺图2: class extends self.ITiledBackgroundInstance {}
}