const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.Particles,
		C3.Behaviors.Pin,
		C3.Behaviors.wrap,
		C3.Plugins.Text,
		C3.Plugins.lobahGameSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetLayoutEffectEnabled,
		C3.Plugins.System.Acts.SetLayerAngle,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Exps.time,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Bullet.Acts.SetGravity,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetLayoutEffectParam,
		C3.Plugins.System.Exps.layerangle,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.lobahGameSDK.Acts.AddScore,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Exps.int,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.TypeScriptInEvents.Sceneadapter_Event1_Act2
	];
};
self.C3_JsPropNameTable = [
	{Sine: 0},
	{Bullet: 0},
	{Brokli: 0},
	{line: 0},
	{next: 0},
	{box: 0},
	{Sprite: 0},
	{Touch: 0},
	{text: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Flash: 0},
	{Sprite8: 0},
	{btnSound: 0},
	{Sprite10: 0},
	{Sprite12: 0},
	{txtScore: 0},
	{touchArea: 0},
	{collect: 0},
	{Star: 0},
	{Keyboard: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{Browser: 0},
	{txtMnScore: 0},
	{txtHighScore: 0},
	{Pin: 0},
	{StarPart: 0},
	{scoresImg: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{bgbulding: 0},
	{Wrap: 0},
	{cloud: 0},
	{btn_back: 0},
	{Text2: 0},
	{lobahGameSDK: 0},
	{choosed: 0},
	{Score: 0},
	{Ready: 0},
	{switch: 0},
	{Change: 0},
	{HighScore: 0},
	{timer: 0},
	{once: 0},
	{adapter: 0},
	{adapterValue: 0},
	{delayAdapter: 0}
];

self.InstanceType = {
	Brokli: class extends self.ISpriteInstance {},
	line: class extends self.ISpriteInstance {},
	box: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	text: class extends self.ISpriteFontInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	btnSound: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	txtScore: class extends self.ISpriteFontInstance {},
	touchArea: class extends self.ISpriteInstance {},
	Star: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	txtMnScore: class extends self.ISpriteFontInstance {},
	txtHighScore: class extends self.ISpriteFontInstance {},
	StarPart: class extends self.IParticlesInstance {},
	scoresImg: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	bgbulding: class extends self.ISpriteInstance {},
	cloud: class extends self.ISpriteInstance {},
	btn_back: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	lobahGameSDK: class extends C3.Plugins.lobahGameSDK.Instance {}
}