const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Behaviors.Pin,
		C3.Plugins.Touch,
		C3.Plugins.Spritefont2,
		C3.Plugins.LocalStorage,
		C3.Plugins.Function,
		C3.Plugins.Text,
		C3.Plugins.Browser,
		C3.Plugins.lobahGameSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Particles.Acts.SetPosToObject,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Spritefont2.Cnds.PickByUID,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Particles.Exps.Count,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Bullet.Exps.DistanceTravelled,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.lobahGameSDK.Acts.AddScore,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.TypeScriptInEvents.Sceneadapter_Event1_Act2
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Center_BG: 0},
	{Direction: 0},
	{GameOver: 0},
	{SetAngle: 0},
	{Bullet: 0},
	{Sine: 0},
	{Sine2: 0},
	{Car: 0},
	{Pin: 0},
	{Ball_Particles: 0},
	{Touch: 0},
	{wall: 0},
	{btn_Play: 0},
	{btn_Volume: 0},
	{btn_Close: 0},
	{MiniBox: 0},
	{Mini_Particles: 0},
	{ScoreSpriteFont: 0},
	{txt_score: 0},
	{LocalStorage: 0},
	{Function: 0},
	{Check_Score: 0},
	{Explode_Ball_Particles: 0},
	{Text: 0},
	{Browser: 0},
	{id: 0},
	{position: 0},
	{btn_back: 0},
	{SpriteFont: 0},
	{Sprite: 0},
	{BG: 0},
	{Sprite2: 0},
	{Score: 0},
	{lobahGameSDK: 0},
	{btn: 0},
	{BestScore: 0},
	{PlayerScore: 0},
	{GameMode: 0},
	{game_high_score: 0},
	{scoretext: 0},
	{adapter: 0},
	{adapterValue: 0},
	{delayAdapter: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Center_BG: class extends self.ISpriteInstance {},
	Car: class extends self.ISpriteInstance {},
	Ball_Particles: class extends self.IParticlesInstance {},
	Touch: class extends self.IInstance {},
	wall: class extends self.ISpriteInstance {},
	btn_Play: class extends self.ISpriteInstance {},
	btn_Volume: class extends self.ISpriteInstance {},
	btn_Close: class extends self.ISpriteInstance {},
	MiniBox: class extends self.ISpriteInstance {},
	Mini_Particles: class extends self.IParticlesInstance {},
	ScoreSpriteFont: class extends self.ISpriteFontInstance {},
	txt_score: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	Check_Score: class extends self.ISpriteInstance {},
	Explode_Ball_Particles: class extends self.IParticlesInstance {},
	Text: class extends self.ITextInstance {},
	Browser: class extends self.IInstance {},
	position: class extends self.ISpriteInstance {},
	btn_back: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Sprite: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Score: class extends self.ISpriteFontInstance {},
	lobahGameSDK: class extends C3.Plugins.lobahGameSDK.Instance {},
	btn: class extends self.ISpriteInstance {}
}