const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Spritefont2,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Behaviors.Flash,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Function,
		C3.Plugins.Audio,
		C3.Plugins.Particles,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Plugins.lobahGameSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.TiledBg.Cnds.CompareY,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.lobahGameSDK.Acts.AddScore,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Function.Exps.ReturnValue,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Function.Cnds.CompareParam,
		C3.Plugins.Particles.Acts.SetPosToObject,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.Function.Acts.SetReturnValue,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Particles.Acts.SetSprayCone,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.lobahGameSDK.Acts.SetGameStatus,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Audio.Acts.UnloadAudio,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.TypeScriptInEvents.Sceneadapter_Event1_Act2
	];
};
self.C3_JsPropNameTable = [
	{btnSound: 0},
	{Sprite16: 0},
	{btnHome: 0},
	{txtScore: 0},
	{create: 0},
	{localspeed: 0},
	{line: 0},
	{lineChange: 0},
	{localspeed2: 0},
	{heckLine: 0},
	{Solid: 0},
	{enemy: 0},
	{bg: 0},
	{Flash: 0},
	{player: 0},
	{hole: 0},
	{LocalStorage: 0},
	{Browser: 0},
	{Keyboard: 0},
	{Touch: 0},
	{Function: 0},
	{btnBack: 0},
	{btnPlay: 0},
	{Sprite6: 0},
	{txtHighScore: 0},
	{Sprite11: 0},
	{txtMnScore: 0},
	{Audio: 0},
	{smoke: 0},
	{LeftTouch: 0},
	{RightTouch: 0},
	{Fade: 0},
	{ballscore: 0},
	{StartLine: 0},
	{Text: 0},
	{lobahGameSDK: 0},
	{crash: 0},
	{speed: 0},
	{rndline: 0},
	{LastScore: 0},
	{Score: 0},
	{CarLine: 0},
	{LLock1: 0},
	{LLock2: 0},
	{LLock3: 0},
	{holeChance: 0},
	{LastLine: 0},
	{canlline1: 0},
	{canlline2: 0},
	{canlline3: 0},
	{pos1: 0},
	{pos2: 0},
	{pos3: 0},
	{enemycount: 0},
	{anyChange: 0},
	{LastYPos: 0},
	{CanLine2Choose: 0},
	{CountL1: 0},
	{CountL2: 0},
	{CountL3: 0},
	{crashLock: 0},
	{loseball: 0},
	{countHole: 0},
	{InAccident: 0},
	{Ready: 0},
	{ConflitCreate: 0},
	{randLine: 0},
	{ver: 0},
	{HighScore: 0},
	{adapter: 0},
	{adapterValue: 0},
	{delayAdapter: 0}
];

self.InstanceType = {
	btnSound: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	btnHome: class extends self.ISpriteInstance {},
	txtScore: class extends self.ISpriteFontInstance {},
	enemy: class extends self.ISpriteInstance {},
	bg: class extends self.ITiledBackgroundInstance {},
	player: class extends self.ISpriteInstance {},
	hole: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	btnBack: class extends self.ISpriteInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	txtHighScore: class extends self.ISpriteFontInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	txtMnScore: class extends self.ISpriteFontInstance {},
	Audio: class extends self.IInstance {},
	smoke: class extends self.IParticlesInstance {},
	LeftTouch: class extends self.ISpriteInstance {},
	RightTouch: class extends self.ISpriteInstance {},
	ballscore: class extends self.ISpriteInstance {},
	StartLine: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	lobahGameSDK: class extends C3.Plugins.lobahGameSDK.Instance {}
}