const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Behaviors.Bullet,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.lobahGameSDK,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.SetLayerEffectEnabled,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Particles.Acts.SetY,
		C3.Plugins.Particles.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.lobahGameSDK.Acts.AddScore,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Spritefont2.Cnds.PickByUID,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.TypeScriptInEvents.Sceneadapter_Event1_Act2
	];
};
self.C3_JsPropNameTable = [
	{Back: 0},
	{Score: 0},
	{Mouse: 0},
	{Score_txt: 0},
	{End_wall: 0},
	{Sine: 0},
	{Play: 0},
	{Touch: 0},
	{Title: 0},
	{Sprite2: 0},
	{Hi_Score_txt: 0},
	{LocalStorage: 0},
	{Browser: 0},
	{Audio: 0},
	{BTNSoundOff: 0},
	{btn_back: 0},
	{BTNHome: 0},
	{Sprite3: 0},
	{Bullet: 0},
	{car: 0},
	{star: 0},
	{left: 0},
	{car2: 0},
	{"2Barrier": 0},
	{Rotate: 0},
	{star2: 0},
	{"2Barrier2": 0},
	{timer: 0},
	{Dood: 0},
	{Sprite4: 0},
	{Particles: 0},
	{Score_txt2: 0},
	{EX: 0},
	{Keyboard: 0},
	{Particles2: 0},
	{Text: 0},
	{lobahGameSDK: 0},
	{Sound: 0},
	{dist: 0},
	{dist2: 0},
	{rand: 0},
	{HiScore: 0},
	{Speed: 0},
	{Run: 0},
	{adapter: 0},
	{adapterValue: 0},
	{delayAdapter: 0}
];

self.InstanceType = {
	Back: class extends self.ISpriteInstance {},
	Score: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Score_txt: class extends self.ISpriteFontInstance {},
	End_wall: class extends self.ISpriteInstance {},
	Play: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Title: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Hi_Score_txt: class extends self.ISpriteFontInstance {},
	LocalStorage: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	BTNSoundOff: class extends self.ISpriteInstance {},
	btn_back: class extends self.ISpriteInstance {},
	BTNHome: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	car: class extends self.ISpriteInstance {},
	star: class extends self.ISpriteInstance {},
	car2: class extends self.ISpriteInstance {},
	_2Barrier: class extends self.ISpriteInstance {},
	star2: class extends self.ISpriteInstance {},
	_2Barrier2: class extends self.ISpriteInstance {},
	timer: class extends self.ISpriteInstance {},
	Dood: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Score_txt2: class extends self.ISpriteFontInstance {},
	EX: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Text: class extends self.ITextInstance {},
	lobahGameSDK: class extends C3.Plugins.lobahGameSDK.Instance {}
}