const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Function,
		C3.Behaviors.Pin,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Flash,
		C3.Plugins.Text,
		C3.Plugins.lobahGameSDK,
		C3.Plugins.TiledBg,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Spritefont2.Cnds.PickByUID,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.lobahGameSDK.Acts.AddScore,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.TypeScriptInEvents.Sceneadapter_Event1_Act2
	];
};
self.C3_JsPropNameTable = [
	{location: 0},
	{isscored: 0},
	{MoveTo: 0},
	{TopPipe: 0},
	{btn_audio: 0},
	{Solid: 0},
	{ScrollTo: 0},
	{Line: 0},
	{jump: 0},
	{Platform: 0},
	{Rotate: 0},
	{Player: 0},
	{Sine: 0},
	{PLAYbtn: 0},
	{SpriteFont: 0},
	{HUD: 0},
	{Touch: 0},
	{Audio: 0},
	{Function: 0},
	{Pin: 0},
	{BottomPipe: 0},
	{checker: 0},
	{TAPTOSTART: 0},
	{HardFLap: 0},
	{LocalStorage: 0},
	{BG: 0},
	{SeedsLoop: 0},
	{Score: 0},
	{splite: 0},
	{EX: 0},
	{BGLoop: 0},
	{Flash: 0},
	{JumpBar: 0},
	{btn_home: 0},
	{Sprite: 0},
	{TXT_Hi_socre: 0},
	{TXT_socre: 0},
	{clouds: 0},
	{Text: 0},
	{lobahGameSDK: 0},
	{平铺图: 0},
	{平铺图2: 0},
	{Speed: 0},
	{PipeSpace: 0},
	{GameMode: 0},
	{BestScore: 0},
	{Sound: 0},
	{adapter: 0},
	{adapterValue: 0},
	{delayAdapter: 0}
];

self.InstanceType = {
	TopPipe: class extends self.ISpriteInstance {},
	btn_audio: class extends self.ISpriteInstance {},
	Line: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	PLAYbtn: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	HUD: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	BottomPipe: class extends self.ISpriteInstance {},
	checker: class extends self.ISpriteInstance {},
	TAPTOSTART: class extends self.ISpriteInstance {},
	HardFLap: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	BG: class extends self.ISpriteInstance {},
	SeedsLoop: class extends self.ISpriteInstance {},
	Score: class extends self.ISpriteInstance {},
	splite: class extends self.ISpriteInstance {},
	EX: class extends self.ISpriteInstance {},
	BGLoop: class extends self.ISpriteInstance {},
	JumpBar: class extends self.ISpriteInstance {},
	btn_home: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TXT_Hi_socre: class extends self.ITextInstance {},
	TXT_socre: class extends self.ITextInstance {},
	clouds: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	lobahGameSDK: class extends C3.Plugins.lobahGameSDK.Instance {},
	平铺图: class extends self.ITiledBackgroundInstance {},
	平铺图2: class extends self.ITiledBackgroundInstance {}
}