const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.scrollto,
		C3.Plugins.Spritefont2,
		C3.Plugins.Function,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Pin,
		C3.Behaviors.Fade,
		C3.Behaviors.Rotate,
		C3.Behaviors.Bullet,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Plugins.lobahGameSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Spritefont2.Cnds.PickByUID,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.lobahGameSDK.Acts.AddScore,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.RotateCounterclockwise,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.TypeScriptInEvents.Sceneadapter_Event1_Act2
	];
};
self.C3_JsPropNameTable = [
	{Splash: 0},
	{DigiSmileLtd: 0},
	{speaker: 0},
	{Sine: 0},
	{PLAY: 0},
	{ScrollTo: 0},
	{Circle: 0},
	{Home: 0},
	{SpriteFont: 0},
	{Function: 0},
	{Best: 0},
	{Touch: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{TAPTOSTART: 0},
	{TeddyEscape: 0},
	{btn_info: 0},
	{increase: 0},
	{decrease: 0},
	{Scale_Size: 0},
	{info_BG: 0},
	{rotate: 0},
	{Pin: 0},
	{Player: 0},
	{Airplane: 0},
	{Explode: 0},
	{Circle2: 0},
	{Circle3: 0},
	{TimeBox: 0},
	{Fade: 0},
	{Rotate: 0},
	{Bullet: 0},
	{Dood: 0},
	{A: 0},
	{Clock: 0},
	{Clock2: 0},
	{Browser: 0},
	{btn_back: 0},
	{Sprite: 0},
	{Text: 0},
	{lobahGameSDK: 0},
	{btn: 0},
	{GameMode: 0},
	{Degress: 0},
	{HighScore: 0},
	{Score: 0},
	{adapter: 0},
	{adapterValue: 0},
	{delayAdapter: 0}
];

self.InstanceType = {
	Splash: class extends self.ISpriteInstance {},
	DigiSmileLtd: class extends self.ISpriteInstance {},
	speaker: class extends self.ISpriteInstance {},
	PLAY: class extends self.ISpriteInstance {},
	Circle: class extends self.ISpriteInstance {},
	Home: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Function: class extends self.IInstance {},
	Best: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	TAPTOSTART: class extends self.ISpriteInstance {},
	TeddyEscape: class extends self.ISpriteInstance {},
	btn_info: class extends self.ISpriteInstance {},
	info_BG: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Airplane: class extends self.ISpriteInstance {},
	Explode: class extends self.ISpriteInstance {},
	Circle2: class extends self.ISpriteInstance {},
	Circle3: class extends self.ISpriteInstance {},
	TimeBox: class extends self.ISpriteInstance {},
	Dood: class extends self.ISpriteInstance {},
	A: class extends self.ISpriteInstance {},
	Clock: class extends self.ISpriteInstance {},
	Clock2: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	btn_back: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	lobahGameSDK: class extends C3.Plugins.lobahGameSDK.Instance {},
	btn: class extends self.ISpriteInstance {}
}