const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.scrollto,
		C3.Behaviors.Pin,
		C3.Plugins.Touch,
		C3.Behaviors.Bullet,
		C3.Plugins.Function,
		C3.Behaviors.wrap,
		C3.Plugins.Spritefont2,
		C3.Plugins.Particles,
		C3.Behaviors.Fade,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Behaviors.Flash,
		C3.Plugins.lobahGameSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Particles.Acts.SetInitSize,
		C3.Plugins.Particles.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Particles.Acts.ZMoveToObject,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.lobahGameSDK.Acts.AddScore,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Behaviors.Sin.Exps.Period,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.lobahGameSDK.Acts.SetGameStatus,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.TypeScriptInEvents.Sceneadapter_Event1_Act2
	];
};
self.C3_JsPropNameTable = [
	{bgmenu: 0},
	{Sine: 0},
	{plmenu: 0},
	{btnPlay: 0},
	{Sprite: 0},
	{bg: 0},
	{ScrollTo: 0},
	{pk: 0},
	{Pin: 0},
	{Layi: 0},
	{kaman: 0},
	{Felesh: 0},
	{Sprite4: 0},
	{Touch: 0},
	{Bullet: 0},
	{ball: 0},
	{Function: 0},
	{Wrap: 0},
	{cloud: 0},
	{Sprite5: 0},
	{txtScore: 0},
	{Particles: 0},
	{btnSound: 0},
	{btn_Back: 0},
	{Fade: 0},
	{fader: 0},
	{LocalStorage: 0},
	{btnHome: 0},
	{Audio: 0},
	{Browser: 0},
	{Sprite6: 0},
	{txtHighScore: 0},
	{txtMnScore: 0},
	{Sprite8: 0},
	{ballscore: 0},
	{touchArea: 0},
	{pkShadow: 0},
	{ballshadow: 0},
	{pkSayeh: 0},
	{ver: 0},
	{txtver: 0},
	{Flash: 0},
	{help: 0},
	{lobahGameSDK: 0},
	{btnballPlay: 0},
	{HighScore: 0},
	{IsLayi: 0},
	{canShoot: 0},
	{loseball: 0},
	{lineCount: 0},
	{shooting: 0},
	{isout: 0},
	{touchleg: 0},
	{Score: 0},
	{once: 0},
	{adapter: 0},
	{adapterValue: 0},
	{delayAdapter: 0}
];

self.InstanceType = {
	bgmenu: class extends self.ISpriteInstance {},
	plmenu: class extends self.ISpriteInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	pk: class extends self.ISpriteInstance {},
	Layi: class extends self.ISpriteInstance {},
	kaman: class extends self.ISpriteInstance {},
	Felesh: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	ball: class extends self.ISpriteInstance {},
	Function: class extends self.IInstance {},
	cloud: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	txtScore: class extends self.ISpriteFontInstance {},
	Particles: class extends self.IParticlesInstance {},
	btnSound: class extends self.ISpriteInstance {},
	btn_Back: class extends self.ISpriteInstance {},
	fader: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	btnHome: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	txtHighScore: class extends self.ISpriteFontInstance {},
	txtMnScore: class extends self.ISpriteFontInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	ballscore: class extends self.ISpriteInstance {},
	touchArea: class extends self.ISpriteInstance {},
	pkShadow: class extends self.ISpriteInstance {},
	ballshadow: class extends self.ISpriteInstance {},
	pkSayeh: class extends self.ISpriteInstance {},
	ver: class extends self.ISpriteInstance {},
	txtver: class extends self.ITextInstance {},
	help: class extends self.ISpriteInstance {},
	lobahGameSDK: class extends C3.Plugins.lobahGameSDK.Instance {}
}