const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch,
		C3.Plugins.Function,
		C3.Behaviors.scrollto,
		C3.Plugins.Spritefont2,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.AJAX,
		C3.Plugins.Browser,
		C3.Plugins.Particles,
		C3.Plugins.lobahGameSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Exps.Text,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.RotateCounterclockwise,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Function.Cnds.CompareParam,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.lobahGameSDK.Acts.AddScore,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.TypeScriptInEvents.Sceneadapter_Event1_Act2
	];
};
self.C3_JsPropNameTable = [
	{BG: 0},
	{Pin: 0},
	{Blocks: 0},
	{Sine: 0},
	{Bullet: 0},
	{Ball: 0},
	{Touch: 0},
	{Function: 0},
	{ScrollTo: 0},
	{PinedObject: 0},
	{SpriteFont: 0},
	{LocalStorage: 0},
	{info: 0},
	{btn_Play: 0},
	{TaptoStart: 0},
	{btn_Audio: 0},
	{btn_home: 0},
	{Audio: 0},
	{HiddenBlock: 0},
	{GameTitle: 0},
	{Text: 0},
	{ScoreC: 0},
	{btnRight: 0},
	{btnleft: 0},
	{AJAX: 0},
	{SpriteFont2: 0},
	{Browser: 0},
	{ParticlesBlue: 0},
	{ParticlesRed: 0},
	{ParticlesYellow: 0},
	{ParticlesGreen: 0},
	{scoreBox: 0},
	{btn_back: 0},
	{lobahGameSDK: 0},
	{BlockRotate: 0},
	{BestScore: 0},
	{BallSpeed: 0},
	{PlayerScore: 0},
	{GameMode: 0},
	{adapter: 0},
	{adapterValue: 0},
	{delayAdapter: 0}
];

self.InstanceType = {
	BG: class extends self.ISpriteInstance {},
	Blocks: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	PinedObject: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	LocalStorage: class extends self.IInstance {},
	info: class extends self.ISpriteInstance {},
	btn_Play: class extends self.ISpriteInstance {},
	TaptoStart: class extends self.ISpriteInstance {},
	btn_Audio: class extends self.ISpriteInstance {},
	btn_home: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	HiddenBlock: class extends self.ISpriteInstance {},
	GameTitle: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	ScoreC: class extends self.ISpriteInstance {},
	btnRight: class extends self.ISpriteInstance {},
	btnleft: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	SpriteFont2: class extends self.ISpriteFontInstance {},
	Browser: class extends self.IInstance {},
	ParticlesBlue: class extends self.IParticlesInstance {},
	ParticlesRed: class extends self.IParticlesInstance {},
	ParticlesYellow: class extends self.IParticlesInstance {},
	ParticlesGreen: class extends self.IParticlesInstance {},
	scoreBox: class extends self.ISpriteInstance {},
	btn_back: class extends self.ISpriteInstance {},
	lobahGameSDK: class extends C3.Plugins.lobahGameSDK.Instance {}
}