const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Flash,
		C3.Plugins.Touch,
		C3.Behaviors.Bullet,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.lobahGameSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.lobahGameSDK.Acts.SetGameStatus,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.lobahGameSDK.Acts.AddScore,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.TypeScriptInEvents.Sceneadapter_Event1_Act2
	];
};
self.C3_JsPropNameTable = [
	{BackGround: 0},
	{Flash: 0},
	{Master: 0},
	{UpRight: 0},
	{UpLeft: 0},
	{DownLeft: 0},
	{DownRight: 0},
	{Touch: 0},
	{dead: 0},
	{Bullet: 0},
	{Sine: 0},
	{Flies: 0},
	{SpriteFont: 0},
	{touchUL: 0},
	{touchUR: 0},
	{touchDR: 0},
	{touchDL: 0},
	{MasterBody: 0},
	{Audio: 0},
	{Fade: 0},
	{Sprite: 0},
	{Play: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Text: 0},
	{txtHighScore: 0},
	{txtMnScore: 0},
	{btnSound: 0},
	{btnHome: 0},
	{scoreBg: 0},
	{txtScore: 0},
	{LocalStorage: 0},
	{Load: 0},
	{scoreFly: 0},
	{Browser: 0},
	{btnBack: 0},
	{Text2: 0},
	{lobahGameSDK: 0},
	{Ready: 0},
	{Hit: 0},
	{Score: 0},
	{Dead: 0},
	{PositionNum: 0},
	{ver: 0},
	{play: 0},
	{HighScore: 0},
	{once: 0},
	{adapter: 0},
	{adapterValue: 0},
	{delayAdapter: 0}
];

self.InstanceType = {
	BackGround: class extends self.ISpriteInstance {},
	Master: class extends self.ISpriteInstance {},
	UpRight: class extends self.ISpriteInstance {},
	UpLeft: class extends self.ISpriteInstance {},
	DownLeft: class extends self.ISpriteInstance {},
	DownRight: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Flies: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	touchUL: class extends self.ISpriteInstance {},
	touchUR: class extends self.ISpriteInstance {},
	touchDR: class extends self.ISpriteInstance {},
	touchDL: class extends self.ISpriteInstance {},
	MasterBody: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Play: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	txtHighScore: class extends self.ISpriteFontInstance {},
	txtMnScore: class extends self.ISpriteFontInstance {},
	btnSound: class extends self.ISpriteInstance {},
	btnHome: class extends self.ISpriteInstance {},
	scoreBg: class extends self.ISpriteInstance {},
	txtScore: class extends self.ISpriteFontInstance {},
	LocalStorage: class extends self.IInstance {},
	Load: class extends self.ISpriteFontInstance {},
	scoreFly: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	btnBack: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	lobahGameSDK: class extends C3.Plugins.lobahGameSDK.Instance {}
}